# Generated by Django 5.2.7 on 2025-11-13 05:31

import helpers.db.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='subdomain',
            field=models.CharField(db_index=True, max_length=60, unique=True, validators=[helpers.db.validators.validate_subdomain, helpers.db.validators.validate_blocked_subdomains]),
        ),
    ]
