# Generated by Django 5.2.7 on 2025-11-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_employeeprofile_hrprofile_delete_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='tenant',
        ),
    ]
