# Generated by Django 5.2.7 on 2025-11-29 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Admin HRs have access to all departments'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='total_leaves',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this HR manages. Leave empty for full access.', related_name='hr_managers', to='accounts.department'),
        ),
    ]
